In [4]:
import pandas as pd
df = pd.read_csv("../data/raw/HI-Small_Trans.csv")
df.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [5]:
df.shape

(5078345, 11)

In [6]:
df.columns.tolist()

['Timestamp',
 'From Bank',
 'Account',
 'To Bank',
 'Account.1',
 'Amount Received',
 'Receiving Currency',
 'Amount Paid',
 'Payment Currency',
 'Payment Format',
 'Is Laundering']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           object
 1   From Bank           int64
 2   Account             object
 3   To Bank             int64
 4   Account.1           object
 5   Amount Received     float64
 6   Receiving Currency  object
 7   Amount Paid         float64
 8   Payment Currency    object
 9   Payment Format      object
 10  Is Laundering       int64
dtypes: float64(2), int64(3), object(6)
memory usage: 426.2+ MB

In [8]:
df.isnull().sum()

Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

In [9]:
df["Is Laundering"].value_counts()

Is Laundering
0    5073168
1       5177
Name: count, dtype: int64

In [10]:
df["Payment Format"].value_counts()

Payment Format
Cheque          1864331
Credit Card     1323324
ACH              600797
Cash             490891
Reinvestment     481056
Wire             171855
Bitcoin          146091
Name: count, dtype: int64

In [11]:

df["Receiving Currency"].value_counts()

Receiving Currency
US Dollar            1879341
Euro                 1172017
Swiss Franc           237884
Yuan                  206551
Shekel                194988
Rupee                 192065
UK Pound              181255
Ruble                 157361
Yen                   156319
Bitcoin               148151
Canadian Dollar       141357
Australian Dollar     138511
Mexican Peso          111030
Saudi Riyal            89971
Brazil Real            71544
Name: count, dtype: int64

In [12]:
df.describe(include="all")

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
count,5078345,5.078345e+06,5078345,5.078345e+06,5078345,5.078345e+06,5078345,5.078345e+06,5078345,5078345,5.078345e+06
unique,15018,NaN,496995,NaN,420636,NaN,15,NaN,15,7,NaN
top,2022/09/01 00:04,NaN,100428660,NaN,100428660,NaN,US Dollar,NaN,US Dollar,Cheque,NaN
freq,11193,NaN,168672,NaN,1084,NaN,1879341,NaN,1895172,1864331,NaN
mean,NaN,4.573057e+04,NaN,6.574456e+04,NaN,5.988726e+06,NaN,4.509273e+06,NaN,NaN,1.019427e-03
std,NaN,8.176562e+04,NaN,8.409299e+04,NaN,1.037183e+09,NaN,8.697728e+08,NaN,NaN,3.191219e-02
min,NaN,1.000000e+00,NaN,1.000000e+00,NaN,1.000000e-06,NaN,1.000000e-06,NaN,NaN,0.000000e+00
25%,NaN,1.190000e+02,NaN,4.259000e+03,NaN,1.833700e+02,NaN,1.844800e+02,NaN,NaN,0.000000e+00
50%,NaN,9.679000e+03,NaN,2.156800e+04,NaN,1.411010e+03,NaN,1.414540e+03,NaN,NaN,0.000000e+00
75%,NaN,2.862800e+04,NaN,1.223320e+05,NaN,1.234627e+04,NaN,1.229784e+04,NaN,NaN,0.000000e+00
max,NaN,3.563030e+05,NaN,3.562940e+05,NaN,1.046302e+12,NaN,1.046302e+12,NaN,NaN,1.000000e+00

In [15]:
print(train_df.head())

NameError: name 'train_df' is not defined

In [14]:
print(train_df.dtypes)

NameError: name 'train_df' is not defined

In [13]:
print(train_df["target"].value_counts())

NameError: name 'train_df' is not defined

In [14]:
df["fraud_type"].value_counts(dropna=False)

fraud_type
NaN                 4820447
card_not_present     179553
Name: count, dtype: int64

In [15]:
df[df["time_since_last_transaction"].isnull()].head()

,transaction_id,timestamp,sender_account,receiver_account,amount,transaction_type,merchant_category,location,device_used,is_fraud,fraud_type,time_since_last_transaction,spending_deviation_score,velocity_score,geo_anomaly_score,payment_channel,ip_address,device_hash
0,T100000,2023-08-22T09:22:43.516168,ACC877572,ACC388389,343.78,withdrawal,utilities,Tokyo,mobile,False,NaN,NaN,-0.21,3,0.22,card,13.101.214.112,D8536477
1,T100001,2023-08-04T01:58:02.606711,ACC895667,ACC944962,419.65,withdrawal,online,Toronto,atm,False,NaN,NaN,-0.14,7,0.96,ACH,172.52.47.194,D2622631
2,T100002,2023-05-12T11:39:33.742963,ACC733052,ACC377370,2773.86,deposit,other,London,pos,False,NaN,NaN,-1.78,20,0.89,card,185.98.35.23,D4823498
3,T100003,2023-10-10T06:04:43.195112,ACC996865,ACC344098,1666.22,deposit,online,Sydney,pos,False,NaN,NaN,-0.60,6,0.37,wire_transfer,107.136.36.87,D9961380
4,T100004,2023-09-24T08:09:02.700162,ACC584714,ACC497887,24.43,transfer,utilities,Toronto,mobile,False,NaN,NaN,0.79,13,0.27,ACH,108.161.108.255,D7637601

In [16]:
df["time_since_last_transaction"].describe()

count    4.103487e+06
mean     1.525799e+00
std      3.576569e+03
min     -8.777814e+03
25%     -2.562376e+03
50%      8.442747e-01
75%      2.568339e+03
max      8.757758e+03
Name: time_since_last_transaction, dtype: float64

In [17]:
df[["time_since_last_transaction",
    "spending_deviation_score",
    "velocity_score",
    "geo_anomaly_score"]].describe()

,time_since_last_transaction,spending_deviation_score,velocity_score,geo_anomaly_score
count,4.103487e+06,5.000000e+06,5.000000e+06,5.000000e+06
mean,1.525799e+00,-3.881160e-04,1.050132e+01,5.000293e-01
std,3.576569e+03,1.000807e+00,5.766842e+00,2.886349e-01
min,-8.777814e+03,-5.260000e+00,1.000000e+00,0.000000e+00
25%,-2.562376e+03,-6.800000e-01,5.000000e+00,2.500000e-01
50%,8.442747e-01,0.000000e+00,1.100000e+01,5.000000e-01
75%,2.568339e+03,6.700000e-01,1.600000e+01,7.500000e-01
max,8.757758e+03,5.020000e+00,2.000000e+01,1.000000e+00

In [18]:
df["timestamp"].head()

0    2023-08-22T09:22:43.516168
1    2023-08-04T01:58:02.606711
2    2023-05-12T11:39:33.742963
3    2023-10-10T06:04:43.195112
4    2023-09-24T08:09:02.700162
Name: timestamp, dtype: object

In [24]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed"
)

In [25]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed",
    errors="coerce"
)

In [26]:
df["timestamp"].isna().sum()

np.int64(0)

In [27]:
df["hour"] = df["timestamp"].dt.hour
df["day_of_week"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [28]:
df[[
    "timestamp",
    "hour",
    "day_of_week",
    "month",
    "is_weekend"
]].head()

                   timestamp  hour  day_of_week  month  is_weekend
0 2023-08-22 09:22:43.516168     9            1      8           0
1 2023-08-04 01:58:02.606711     1            4      8           0
2 2023-05-12 11:39:33.742963    11            4      5           0
3 2023-10-10 06:04:43.195112     6            1     10           0
4 2023-09-24 08:09:02.700162     8            6      9           1